import { db } from "./db";
import { users, drivers, organizations } from "@shared/schema";
import { eq } from "drizzle-orm";
import bcrypt from "bcryptjs";
import { randomBytes } from "crypto";

export async function bootstrapAdminUser(): Promise<void> {
  await bootstrapRootSuperAdmin();
}

export async function bootstrapRootSuperAdmin(): Promise<void> {
  const rootEmail = (process.env.ROOT_SUPER_ADMIN_EMAIL || "will@driverondemand.co").toLowerCase();
  const orgName = process.env.ROOT_PRODUCTION_ORG_NAME || "Driver on Demand";
  const orgEnv = process.env.ROOT_PRODUCTION_ORG_ENV || "production";
  const rootPassword = process.env.ROOT_SUPER_ADMIN_PASSWORD;

  try {
    // Step A: Ensure production org exists
    let productionOrgId: string;
    const orgSlug = orgName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

    const [existingOrg] = await db
      .select()
      .from(organizations)
      .where(eq(organizations.environment, orgEnv))
      .limit(1);

    if (!existingOrg) {
      const newOrgId = crypto.randomUUID();
      await db.insert(organizations).values({
        id: newOrgId,
        name: orgName,
        slug: orgSlug,
        environment: orgEnv,
        isActive: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      productionOrgId = newOrgId;
      console.log(`[Bootstrap] Production org created: ${newOrgId} (${orgName})`);
    } else {
      productionOrgId = existingOrg.id;
      console.log(`[Bootstrap] Production org ensured: ${productionOrgId} (${existingOrg.name})`);
    }

    // Step B: Ensure root super admin exists and is linked to production org
    const [existingUser] = await db
      .select()
      .from(users)
      .where(eq(users.email, rootEmail))
      .limit(1);

    if (!existingUser) {
      let initialPassword = rootPassword;
      let autoGenerated = false;
      if (!initialPassword) {
        initialPassword = randomBytes(16).toString("base64url");
        autoGenerated = true;
      }
      const passwordHash = await bcrypt.hash(initialPassword, 12);

      await db.insert(users).values({
        id: crypto.randomUUID(),
        email: rootEmail,
        firstName: "Will",
        lastName: "",
        role: "super_user",
        status: "ACTIVE",
        passwordHash,
        isProvisioned: true,
        isRootSuperAdmin: true,
        orgId: productionOrgId,
        forcePasswordReset: autoGenerated,
        createdAt: new Date(),
        updatedAt: new Date(),
      });

      if (autoGenerated) {
        console.log(`[Bootstrap] Root super admin created: ${rootEmail}`);
        console.warn(`[Bootstrap] *** TEMP PASSWORD (set ROOT_SUPER_ADMIN_PASSWORD secret): ${initialPassword} ***`);
      } else {
        console.log(`[Bootstrap] Root super admin created: ${rootEmail} (password from secret)`);
      }
    } else {
      // Ensure the root account stays linked to the production org. Never
      // overwrite an existing password during application startup: doing so
      // invalidates the user's prior credential on every deploy.
      const updates: Record<string, any> = {
        role: "super_user",
        isRootSuperAdmin: true,
        status: "ACTIVE",
        orgId: productionOrgId,
        isProvisioned: true,
        updatedAt: new Date(),
      };

      if (rootPassword && (!existingUser.passwordHash || existingUser.passwordHash.trim() === "")) {
        updates.passwordHash = await bcrypt.hash(rootPassword, 12);
        updates.forcePasswordReset = false;
      }

      await db.update(users).set(updates).where(eq(users.id, existingUser.id));

      if (rootPassword && (!existingUser.passwordHash || existingUser.passwordHash.trim() === "")) {
        console.log(`[Bootstrap] Root super admin ensured: ${rootEmail} (password initialized from secret)`);
      } else {
        console.log(`[Bootstrap] Root super admin ensured: ${rootEmail}`);
      }
    }
  } catch (error) {
    console.error("[Bootstrap] CRITICAL — Failed to bootstrap production org/root admin:", error);
  }
}
