/**
 * Weekly Report Service  (Ticket 3.2)
 *
 * For each account with sendWeeklyReport = true:
 *   1. Fetches account contacts + email configuration
 *   2. Generates PDF schedule + Excel hours files
 *   3. Skips delivery if no files were generated or no valid email present
 *   4. Emails via Microsoft Graph with both files as attachments
 *   5. Logs the delivery result to report_delivery_logs
 *
 * Email format:
 *   Subject: Weekly Driver Schedule & Hours – {Account Name} – Week of {WeekStartDate}
 *   Body:    Hi {Contact Name}, Attached are your weekly reports…
 *   Attachments: Schedule_{Account}_{Week}.pdf, Hours_{Account}_{Week}.xlsx
 */

import { db } from "../db";
import { sql } from "drizzle-orm";
import { sendEmail, isMicrosoftGraphConfigured, assertMs365GlobalPrereqs, assertMailboxOperational, VALID_MAILBOX_PROFILES } from "./microsoftGraphService";
import { generateSchedulePdf as generateProfessionalSchedulePdf } from "./scheduleReportPdfService";
import { storeScheduleReport } from "./scheduleReportStorageService";
import { generateHoursExcel } from "./hoursReportExcelService";
import { storeHoursReport } from "./hoursReportStorageService";
import { getUpcomingWeekBounds } from "./weeklyGenerationService";

// ── Friendly date format — "March 31, 2026" ───────────────────────────────────
function fmtDate(iso: string): string {
  const [y, m, d] = iso.split("-").map(Number);
  return new Date(y, m - 1, d).toLocaleDateString("en-US", {
    month: "long", day: "numeric", year: "numeric",
  });
}

// ── Email body template (spec-compliant) ──────────────────────────────────────
function buildEmailBody(
  accountName: string,
  weekStart:   string,
  weekEnd:     string,
): string {
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: Arial, sans-serif; color: #333; font-size: 14px; line-height: 1.6; margin: 0; padding: 0; }
  .header { background-color: #1F2A6D; color: white; padding: 20px 30px; }
  .header h1 { margin: 0; font-size: 18px; font-weight: 600; letter-spacing: 0.01em; }
  .header p { margin: 4px 0 0; font-size: 13px; opacity: 0.75; }
  .body { padding: 28px 30px; }
  .footer { padding: 16px 30px; font-size: 11px; color: #aaa; border-top: 1px solid #eee; }
</style></head>
<body>
  <div class="header">
    <h1>Driver on Demand</h1>
    <p>Weekly Report &mdash; ${accountName}</p>
  </div>
  <div class="body">
    <p>Attached is your weekly report for <strong>${accountName}</strong> &mdash; Week of ${fmtDate(weekStart)}.</p>
    <p>Please let us know if you have any questions or need adjustments.</p>
    <p>Best regards,<br>Driver on Demand Team</p>
  </div>
  <div class="footer">
    Generated by DriverHub 360 &mdash; Week: ${weekStart} &ndash; ${weekEnd}
  </div>
</body>
</html>`.trim();
}

// ── Core per-account send function ───────────────────────────────────────────
export interface AccountReportResult {
  customerId:  string;
  accountName: string;
  status:      "success" | "failed" | "skipped" | "blocked";
  emailTo?:    string;
  emailCc?:    string;
  error?:      string;
  logId?:      string;
  blockedChecks?: string[];
}

export interface SendOverrides {
  recipientEmails?: string[];
  ccEmails?: string[];
}

export async function sendAccountWeeklyReport(
  customerId: string,
  weekStart?: string,
  weekEnd?: string,
  overrides?: SendOverrides
): Promise<AccountReportResult> {
  const bounds = getUpcomingWeekBounds();
  const ws = weekStart ?? bounds.weekStart;
  const we = weekEnd   ?? bounds.weekEnd;

  // ── Fetch account ─────────────────────────────────────────────────────────
  const accRaw = await db.execute(sql`
    SELECT id, customer_name,
           report_contact_name, primary_contact_name,
           report_primary_email, report_primary_emails, report_cc_emails,
           primary_contact_email,
           include_schedule_pdf, include_hours_excel,
           report_sender_profile
    FROM customers
    WHERE id = ${customerId} AND is_deleted = false
    LIMIT 1
  `);
  const acc: any = ((accRaw as any).rows ?? accRaw)[0];
  if (!acc) return { customerId, accountName: "Unknown", status: "failed", error: "Account not found" };

  // Resolve sender profile (validated against known profiles; falls back to Reports)
  const senderProfile = VALID_MAILBOX_PROFILES.includes(acc.report_sender_profile ?? "")
    ? acc.report_sender_profile
    : "Reports";

  // Per-mailbox gate: block if the configured mailbox is not fully pass
  const gate = await assertMailboxOperational(senderProfile, { reportType: "per_account_report", accountId: customerId });
  if (!gate.ok) {
    const reason = gate.reason ?? "Report blocked. Selected sender mailbox is not operational.";
    await logDelivery(customerId, ws, we, "blocked", null, null, 0, null, reason);
    return { customerId, accountName: acc.customer_name ?? "Unknown", status: "blocked", error: reason, blockedChecks: gate.failedChecks };
  }
  const fromEmail = gate.resolvedEmail;

  const accountName  = acc.customer_name;

  // Resolve primary recipient: override → array field → singular field → primary contact email
  let configuredEmailsList: string[] = [];
  try { configuredEmailsList = JSON.parse(acc.report_primary_emails ?? "[]"); } catch {}
  const configuredEmailTo = (configuredEmailsList.length > 0 ? configuredEmailsList[0] : null)
    || acc.report_primary_email
    || acc.primary_contact_email
    || null;

  // Apply overrides if provided
  const emailToList: string[] = (overrides?.recipientEmails && overrides.recipientEmails.length > 0)
    ? overrides.recipientEmails
    : configuredEmailsList.length > 0
      ? configuredEmailsList
      : configuredEmailTo ? [configuredEmailTo] : [];

  const emailTo = emailToList[0] ?? null;

  let emailCcList: string[] = [];
  if (overrides?.ccEmails && overrides.ccEmails.length > 0) {
    emailCcList = overrides.ccEmails;
  } else {
    try { emailCcList = JSON.parse(acc.report_cc_emails ?? "[]"); } catch {}
  }
  const GLOBAL_CC = "da@driverondemand.co";
  if (!emailCcList.includes(GLOBAL_CC) && !emailToList.includes(GLOBAL_CC)) {
    emailCcList = [...emailCcList, GLOBAL_CC];
  }
  const emailCcStr = emailCcList.join(", ");

  // ── Check credentials ─────────────────────────────────────────────────────
  if (!isMicrosoftGraphConfigured()) {
    await logDelivery(customerId, ws, we, "skipped", emailTo, emailCcStr, 0, null, "Microsoft Graph not configured");
    return { customerId, accountName, status: "skipped", emailTo: emailTo ?? undefined, error: "Microsoft Graph not configured" };
  }

  // ── Skip if no valid email present ───────────────────────────────────────
  if (!emailTo) {
    await logDelivery(customerId, ws, we, "skipped", null, emailCcStr, 0, null, "No email address configured for account");
    return { customerId, accountName, status: "skipped", error: "No email address configured" };
  }

  try {
    // ── Generate PDF only (Excel deferred — not sent to customers yet) ────────
    let pdfResult: Awaited<ReturnType<typeof generateProfessionalSchedulePdf>> | null = null;
    const generationErrors: string[] = [];

    try {
      pdfResult = await generateProfessionalSchedulePdf({ customerId, accountName, weekStart: ws, weekEnd: we });
    } catch (e: any) {
      generationErrors.push(`PDF: ${e.message}`);
    }

    // ── Skip if no PDF generated ──────────────────────────────────────────
    if (!pdfResult || pdfResult.buffer.length <= 100) {
      const reason = generationErrors.length > 0
        ? generationErrors.join("; ")
        : "No schedule data available for this week";
      await logDelivery(customerId, ws, we, "skipped", emailTo, emailCcStr, 0, null, reason);
      return { customerId, accountName, status: "skipped", emailTo, error: reason };
    }

    // ── Archive PDF to Object Storage (best-effort) ───────────────────────
    try {
      await storeScheduleReport({
        customerId, accountName, weekStart: ws, weekEnd: we,
        buffer: pdfResult.buffer, fileName: pdfResult.fileName,
        shiftCount: pdfResult.shiftCount, driverCount: pdfResult.driverCount,
        uploadedByUserId: null,
      });
    } catch (storErr: any) {
      console.warn("[WeeklyReport] Archive storage failed (non-fatal):", storErr.message);
    }

    // ── Build attachment list (PDF only) ──────────────────────────────────
    const accountSlug = accountName.replace(/[^a-z0-9]/gi, "_");
    const weekLabel   = ws.replace(/-/g, "");
    const attachments: { name: string; contentType: string; contentBytes: string }[] = [
      {
        name:         `Schedule_${accountSlug}_${weekLabel}.pdf`,
        contentType:  "application/pdf",
        contentBytes: pdfResult.buffer.toString("base64"),
      },
    ];

    // ── Send email ─────────────────────────────────────────────────────────
    const subject  = `Weekly Report \u2013 ${accountName} \u2013 Week of ${fmtDate(ws)}`;
    const bodyHtml = buildEmailBody(accountName, ws, we);

    const emailToStr = emailToList.join(", ");
    const result = await sendEmail({
      to:        emailToList,
      cc:        emailCcList.length > 0 ? emailCcList : undefined,
      subject,
      bodyHtml,
      attachments,
      fromEmail, // use the validated profile mailbox email
    });

    if (result.ok) {
      await logDelivery(customerId, ws, we, "success", emailToStr, emailCcStr, attachments.length, new Date(), null);
      return { customerId, accountName, status: "success", emailTo: emailToStr, emailCc: emailCcStr };
    } else {
      const errMsg = result.skipped ? "Microsoft Graph not configured" : (result.error ?? "Send failed");
      await logDelivery(customerId, ws, we, result.skipped ? "skipped" : "failed", emailToStr, emailCcStr, 0, null, errMsg);
      return { customerId, accountName, status: result.skipped ? "skipped" : "failed", emailTo: emailToStr, error: errMsg };
    }

  } catch (err: any) {
    const errMsg = err?.message ?? String(err);
    await logDelivery(customerId, ws, we, "failed", emailTo, emailCcStr, 0, null, errMsg.slice(0, 500));
    return { customerId, accountName, status: "failed", emailTo, error: errMsg };
  }
}

// ── Log delivery attempt ──────────────────────────────────────────────────────
async function logDelivery(
  customerId: string,
  weekStart: string,
  weekEnd: string,
  status: string,
  emailTo: string | null,
  emailCc: string | null,
  attachmentCount: number,
  sentAt: Date | null,
  errorMessage: string | null
) {
  try {
    await db.execute(sql`
      INSERT INTO report_delivery_logs
        (customer_id, report_week_start, report_week_end, status, email_to, email_cc,
         attachment_count, sent_at, error_message, created_at)
      VALUES
        (${customerId}, ${weekStart}::date, ${weekEnd}::date, ${status},
         ${emailTo}, ${emailCc}, ${attachmentCount},
         ${sentAt ? sentAt.toISOString() : null}::timestamp,
         ${errorMessage}, NOW())
    `);
  } catch (logErr: any) {
    console.error("[WeeklyReport] Failed to write delivery log:", logErr?.message);
  }
}

// ── Weekly batch runner (called by scheduler) ─────────────────────────────────
export interface WeeklyReportBatchResult {
  attempted:      number;
  succeeded:      number;
  skipped:        number;
  failed:         number;
  errors:         string[];
  blocked?:       boolean;
  blockedReason?: string;
  blockedChecks?: string[];
}

export async function runWeeklyReportBatch(): Promise<WeeklyReportBatchResult> {
  const result: WeeklyReportBatchResult = { attempted: 0, succeeded: 0, skipped: 0, failed: 0, errors: [] };
  const { weekStart, weekEnd } = getUpcomingWeekBounds();

  // Hard gate: block entire batch if MS365 integration is not fully operational
  // Batch-level gate: only blocks if global prereqs (secrets/OAuth) are broken.
  // Per-account mailbox status is evaluated inside sendAccountWeeklyReport.
  const gate = await assertMs365GlobalPrereqs({ reportType: "weekly_report_batch" });
  if (!gate.ok) {
    const reason = gate.reason ?? "Microsoft 365 Email integration is not fully operational.";
    console.warn("[WeeklyReport] Batch BLOCKED — MS365 integration not fully operational.");
    console.warn(`[WeeklyReport] Reason: ${reason}`);
    if (gate.failedChecks?.length) console.warn(`[WeeklyReport] Failed checks: ${gate.failedChecks.join("; ")}`);
    return { ...result, blocked: true, blockedReason: reason, blockedChecks: gate.failedChecks };
  }

  try {
    const accountsRaw = await db.execute(sql`
      SELECT id, customer_name
      FROM customers
      WHERE send_weekly_report = true
        AND is_deleted = false
        AND status = 'Active'
      ORDER BY customer_name
    `);
    const accounts: any[] = (accountsRaw as any).rows ?? [];

    for (const acc of accounts) {
      result.attempted++;
      try {
        const r = await sendAccountWeeklyReport(acc.id, weekStart, weekEnd);
        if (r.status === "success") result.succeeded++;
        else if (r.status === "skipped") result.skipped++;
        else {
          result.failed++;
          result.errors.push(`${acc.customer_name}: ${r.error ?? "unknown error"}`);
        }
      } catch (e: any) {
        result.failed++;
        result.errors.push(`${acc.customer_name}: ${e?.message ?? e}`);
      }
    }
  } catch (outerErr: any) {
    result.errors.push(`Batch init error: ${outerErr?.message ?? outerErr}`);
  }

  console.log(
    `[WeeklyReport] Batch complete: attempted=${result.attempted}, success=${result.succeeded}, ` +
    `skipped=${result.skipped}, failed=${result.failed}`
  );
  return result;
}
